#_*_ coding:utf-8 _*_

#根据后缀匹配文件类型
dic1 = {'ma5': 'audio', 'fh5': 'image', 'aam': 'application', 'nokia-op-logo': 'image', 
    'hdm': 'text', 'jam': 'application', 'sgm': 'text', 'qtif': 'image', 'pgm': 'image', 
    'skt': 'application', 'ram': 'audio', 'mrm': 'application', 'pnm': 'image', 
    'skm': 'application', 'thm': 'application', 'vrt': 'x-world', 'xdm': 'application', 
    'trm': 'application', 'xht': 'application', 'wmls': 'text', 'evy': 'application', 
    'dir': 'application', 'toy': 'image', 'ivr': 'i-world', 'svr': 'x-world', 
    'spr': 'application', 'm3u': 'audio', 'tkined': 'application', 'xlw': 'application', 
    'ccn': 'application', 'ustar': 'application', 'mocha': 'application', 'mdz': 'audio', 
    'aas': 'application', 'tgz': 'application', 'taz': 'application', 'ins': 'application', 
    'ras': 'image', 'pnz': 'image', 'ndwn': 'application', 'wrz': 'x-world', 'ptlk': 'application', 
    'xyz': 'chemical', 'tex': 'application', 'smil': 'application', 'm4a': 'audio', 'fpx': 'image', 
    'vox': 'audio', 'asx': 'video', 'lcc': 'application', 'amc': 'application', 'lsx': 'video', 
    'npx': 'application', 'wvx': 'video', 'etc': 'application', 'ipx': 'application', 
    'sv4crc': 'application', 'pvx': 'video', 'jwc': 'application', 'rwc': 'application', 
    'lgh': 'application', 'oda': 'application', 'lha': 'application', 'pda': 'image', 
    'mov': 'video', 'shar': 'application', 'viv': 'video', 'rmvb': 'audio', 'bld2': 'application', 
    'tsv': 'text', 'mzv': 'application', 'dhtml': 'text', 'cdf': 'application', 'j2k': 'image', 
    'wmlc': 'application', 'hdf': 'application', 'sdf': 'application', 'rdf': 'application', 
    'pdf': 'application', 'ebk': 'application', 'cod': 'image', 'mp3': 'audio', 'mbd': 'application', 
    'bld': 'application', 'mod': 'audio', 'bpk': 'application', 'mid': 'audio', 'apk': 'application', 
    'asd': 'application', 'movie': 'video', 'texinfo': 'application', 'bmp': 'image', 'emb': 'chemical', 
    'qcp': 'audio', 'smp': 'application', 'vmi': 'application', 'awb': 'audio', 'smi': 'application', 
    'qti': 'image', 'pqi': 'application', 'm14': 'application', 'html': 'text', 'dmg': 'application', 
    'dwg': 'application', 'rtg': 'application', 'fh4': 'image', 'cal': 'image', 'mrl': 'text', 
    'pae': 'audio', 'wrl': 'x-world', 'uue': 'application', 'vivo': 'video', 'vre': 'x-world', 
    'embl': 'chemical', 'xul': 'text', 'si9': 'image', 'pict': 'image', 'mp2': 'audio', 'bz2': 'application', 
    'au': 'audio', 'ra': 'audio', 'sh': 'application', 'uu': 'application', 'tr': 'application', 
    'mpeg': 'video', 'jpeg': 'image', 'r3t': 'text', 's3m': 'audio', 'xhtm': 'application', 
    'si7': 'image', 'mio': 'audio', 'dcm': 'x-lml', 'mct': 'application', 'ifm': 'image', 
    'rmm': 'audio', 'htm': 'text', 'stm': 'audio', 'txt': 'text', 'mpgvideo/mpeg': '', 
    'shtml': 'magnus-internal', 'nar': 'application', 'mny': 'application', 'jar': 'application', 
    'cur': 'application', 'tar': 'application', 'rar': 'application', 'xar': 'application', 
    'sv4cpio': 'application', 'mpg4': 'video', 'conf': 'text', 'xsit': 'text', 'latex': 'application', 
    'bcpio': 'application', 'x-gzip': 'application', 'xdw': 'application', 'shw': 'application', 
    'vrw': 'x-world', 's3z': 'audio', 'java': 'text', 'aifc': 'audio', 'bin': 'application', 
    'swfl': 'application', 'asn': 'application', 'mpn': 'application', 'dms': 'application', 
    'nmz': 'application', 'ifs': 'image', 'wmz': 'application', 'mtz': 'application', 'smz': 'audio', 
    'vms': 'application', 'itz': 'audio', 'mts': 'application', 'ttz': 'application', 'hts': 'text', 
    'vts': 'workbook', 'xmz': 'audio', 'wax': 'audio', 'doc': 'application', 'rnx': 'application', 
    'moc': 'application', 'asc': 'text', 'toc': 'application', 'slc': 'application', 'mpc': 'application', 
    'wsc': 'application', 'xlc': 'application', 'spc': 'text', 'm4v': 'video', 'gca': 'application', 
    'jnlp': 'application', 'sca': 'application', 'wma': 'audio', 'gtar': 'application', 'wav': 'audio', 
    'm13': 'application', 'class': 'application', 'dwf': 'drawing', 'mmf': 'application', 'vcf': 'text', 
    'wmf': 'application', 'vmf': 'application', 'rmf': 'audio', 'dxf': 'application', 'swf': 'application', 
    'ttf': 'application', 'vqf': 'audio', 'ma3': 'audio', 'rtf': 'application', 'mpga': 'audio', 
    'pqf': 'application', 'lak': 'x-lml', 'jad': 'text', 'crd': 'application', 'tad': 'application', 
    'snd': 'audio', 'skd': 'application', 'trk': 'x-lml', 'clp': 'application', 'mop': 'chemical', 
    'xhtml': 'application', 'fvi': 'video', 'tbp': 'application', 'dvi': 'application', 'asp': 'application', 
    'cpp': 'text', 'avi': 'video', 'web': 'application', 'hlp': 'application', 'avb': 'application', 
    'mpp': 'application', 'tsp': 'application', 'vib': 'audio', 'zip': 'application', 'tsi': 'audio', 
    'yz1': 'application', 'xpi': 'application', 'nsnd': 'audio', 'docx': 'application', 'csml': 'chemical', 
    'si6': 'image', 'log': 'text', 'msg': 'application', 'jpg': 'image', 'svg': 'image', 'lcl': 'application', 
    'wmlsc': 'application', 'lml': 'x-lml', 'ice': 'x-conference', 'tcl': 'application', 'wml': 'text', 
    'wmlscript': 'text', 'exe': 'application', 'vql': 'audio', 'xml': 'text', 'vqe': 'audio', 'ma2': 'audio', 
    'rte': 'x-lml', 'wxl': 'application', 'fm': 'application', 'nc': 'application', 'rf': 'image', 'rc': 'text', 
    'wm': 'video', 'rm': 'audio', 'it': 'audio', 'pm': 'application', 'rt': 'text', 'qt': 'video', 'xm': 'audio', 
    'aiff': 'audio', 'roff': 'application', 'tiff': 'image', 'vdo': 'video', 'cpio': 'application', 'dot': 'application', 
    'oom': 'application', 'tbt': 'application', 'evm': 'x-lml', 'cpt': 'application', 'csm': 'chemical', 'ult': 'audio', 
    'pot': 'application', 'pbm': 'image', 'sit': 'application', 'wpt': 'x-lml', 'xbm': 'image', 'xlt': 'application', 
    'spt': 'application', 'ppt': 'application', 'xlm': 'application', 'rpm': 'audio', 'dcr': 'application', 
    'ppm': 'image', 'lcr': 'application', 'xpm': 'image', 'imy': 'audio', 'pfr': 'application', 'sprite': 'application', 
    'dxr': 'application', 'm4u': 'video', 'gau': 'chemical', 'man': 'application', 'pan': 'application', 'als': 'audio', 
    'talk': 'text', 'gps': 'application', 'css': 'text', 'eps': 'application', 'wis': 'application', 'jpz': 'image', 
    'mps': 'application', 'sis': 'application', 'ips': 'application', 'wps': 'application', 'xls': 'application', 'dcx': 'image', 
    'pps': 'application', 'cmx': 'application', 'etx': 'text', 'kjx': 'application', 'wmx': 'video', 'pcx': 'image', 'mtx': 'application', 
    'fhc': 'image', 'wpng': 'image', 'hqx': 'application', 'rtx': 'text', 'pac': 'audio', 'zac': 'application', 'src': 'application', 
    'prc': 'application', 'lmlpack': 'x-lml', 'csh': 'application', 'pptx': 'application', 'sea': 'application', 'nva': 'application', 
    'svh': 'image', 'lzh': 'application', 'xla': 'application', 'wmv': 'audio', 'gif': 'image', 'fif': 'image', 'ief': 'image', 
    'mof': 'application', 'aif': 'audio', 'nif': 'application', 'mif': 'application', 'asf': 'video', '3gp': 'video', 'lsf': 'video', 
    'rlf': 'application', 'tif': 'image', 'svf': 'image', 'm4p': 'audio', 'm4b': 'audio', 'vcd': 'application', 'scd': 'application', 
    'wmd': 'application', 'vmd': 'application', 'smd': 'audio', '': '*', 'pmd': 'application', 'prop': 'text', 'stk': 'application', 
    'ma1': 'audio', 'cgi': 'magnus-internal', 'gdb': 'x-lml', 'nbmp': 'image', 'xwd': 'image', 'map': 'magnus-internal', 'ani': 'application', 
    'wbmp': 'image', 'aab': 'application', 'mdb': 'application', 'ndb': 'x-lml', 'eri': 'image', 'm3url': 'audio', 'midi': 'audio', 
    'skp': 'application', 'rgb': 'image', 'tki': 'application', 'pdb': 'chemical', 'wri': 'application', 'pub': 'application', 
    'xlsx': 'application', 'hdml': 'text', 'sgml': 'text', 'ogg': 'audio', 'vrml': 'x-world', 'mng': 'video', 'png': 'image', 
    'mel': 'text', 'dll': 'application', 'mol': 'chemical', 'mp4': 'video', 'esl': 'audio', 'c': 'text', 'mil': 'image', 'h': 'text', 
    'mpe': 'video', 't': 'application', 'xdma': 'application', 'jpe': 'image', 'xll': 'application', 'spl': 'application', 'z': 'application', 
    'xsl': 'text', 'co': 'application', 'me': 'application', 'ai': 'application', 'es': 'audio', 'mi': 'application', 'gz': 'application', 
    'wi': 'image', 'ms': 'application', 'js': 'application', 'wv': 'video', 'ws': 'text', 'chat': 'application', 'rv': 'video', 
    'ps': 'application', 'rp': 'image', 'texi': 'application', 'm15': 'audio', 'proxy': 'application', 'cco': 'application', 'ico': 'application'}

#根据文件类型匹配后缀
dic2 = {'application': ['aam', 'jam', 'skt', 'mrm', 'skm', 'thm', 'xdm', 'trm', 'xht', 'evy', 'dir', 'spr', 'tkined', 'xlw', 'ccn', 'ustar', 
                        'mocha', 'aas', 'tgz', 'taz', 'ins', 'ndwn', 'ptlk', 'tex', 'smil', 'lcc', 'amc', 'npx', 'etc', 'ipx', 'sv4crc', 'jwc', 
                        'rwc', 'lgh', 'oda', 'lha', 'shar', 'bld2', 'mzv', 'cdf', 'wmlc', 'hdf', 'sdf', 'rdf', 'pdf', 'ebk', 'mbd', 'bld', 'bpk', 
                        'apk', 'asd', 'texinfo', 'smp', 'vmi', 'smi', 'pqi', 'm14', 'dmg', 'dwg', 'rtg', 'uue', 'bz2', 'sh', 'uu', 'tr', 'xhtm', 
                        'mct', 'nar', 'mny', 'jar', 'cur', 'tar', 'rar', 'xar', 'sv4cpio', 'latex', 'bcpio', 'x-gzip', 'xdw', 'shw', 'bin', 'swfl', 
                        'asn', 'mpn', 'dms', 'nmz', 'wmz', 'mtz', 'vms', 'mts', 'ttz', 'doc', 'rnx', 'moc', 'toc', 'slc', 'mpc', 'wsc', 'xlc', 'gca', 
                        'jnlp', 'sca', 'gtar', 'm13', 'class', 'mmf', 'wmf', 'vmf', 'dxf', 'swf', 'ttf', 'rtf', 'pqf', 'crd', 'tad', 'skd', 'clp', 
                        'xhtml', 'tbp', 'dvi', 'asp', 'web', 'hlp', 'avb', 'mpp', 'tsp', 'zip', 'yz1', 'xpi', 'docx', 'msg', 'lcl', 'wmlsc', 'tcl', 
                        'exe', 'wxl', 'fm', 'nc', 'pm', 'roff', 'cpio', 'dot', 'oom', 'tbt', 'cpt', 'pot', 'sit', 'xlt', 'spt', 'ppt', 'xlm', 'dcr', 
                        'lcr', 'pfr', 'sprite', 'dxr', 'man', 'pan', 'gps', 'eps', 'wis', 'mps', 'sis', 'ips', 'wps', 'xls', 'pps', 'cmx', 'kjx', 'mtx', 
                        'hqx', 'zac', 'src', 'prc', 'csh', 'pptx', 'sea', 'nva', 'lzh', 'xla', 'mof', 'nif', 'mif', 'rlf', 'vcd', 'scd', 'wmd', 'vmd', 
                        'pmd', 'stk', 'ani', 'aab', 'mdb', 'skp', 'tki', 'wri', 'pub', 'xlsx', 'dll', 't', 'xdma', 'xll', 'spl', 'z', 'co', 'me', 'ai', 
                        'mi', 'gz', 'ms', 'js', 'chat', 'ps', 'texi', 'proxy', 'cco', 'ico'], 
        '': ['mpgvideo/mpeg'], 'magnus-internal': ['shtml', 'cgi', 'map'], 'x-conference': ['ice'], 
        'video': ['asx', 'lsx', 'wvx', 'pvx', 'mov', 'viv', 'movie', 'vivo', 'mpeg', 'mpg4', 'm4v', 'fvi', 'avi', 'wm', 'qt', 'vdo', 'm4u', 'wmx', 'asf', 
                  '3gp', 'lsf', 'mng', 'mp4', 'mpe', 'wv', 'rv'], 
        'text': ['hdm', 'sgm', 'wmls', 'tsv', 'dhtml', 'html', 'mrl', 'xul', 'r3t', 'htm', 'txt', 'conf', 'xsit', 'java', 'hts', 'asc', 'spc', 'vcf', 'jad', 
                 'cpp', 'log', 'wml', 'wmlscript', 'xml', 'rc', 'rt', 'talk', 'css', 'etx', 'rtx', 'prop', 'hdml', 'sgml', 'mel', 'c', 'h', 'xsl', 'ws'], 
        'x-world': ['vrt', 'svr', 'wrz', 'wrl', 'vre', 'vrw', 'vrml'], 
        'audio': ['ma5', 'ram', 'm3u', 'mdz', 'm4a', 'vox', 'rmvb', 'mp3', 'mod', 'mid', 'qcp', 'awb', 'pae', 'mp2', 'au', 'ra', 's3m', 'mio', 'rmm', 'stm', 
                  's3z', 'aifc', 'smz', 'itz', 'xmz', 'wax', 'wma', 'wav', 'rmf', 'vqf', 'ma3', 'mpga', 'snd', 'vib', 'tsi', 'nsnd', 'vql', 'vqe', 'ma2', 'rm', 
                  'it', 'xm', 'aiff', 'ult', 'rpm', 'imy', 'als', 'pac', 'wmv', 'aif', 'm4p', 'm4b', 'smd', 'ma1', 'm3url', 'midi', 'ogg', 'esl', 'es', 'm15'], 
        'x-lml': ['dcm', 'lak', 'trk', 'lml', 'rte', 'evm', 'wpt', 'lmlpack', 'gdb', 'ndb'], 
        'image': ['fh5', 'nokia-op-logo', 'qtif', 'pgm', 'pnm', 'toy', 'ras', 'pnz', 'fpx', 'pda', 'j2k', 'cod', 'bmp', 'qti', 'fh4', 'cal', 'si9', 'pict', 
                  'jpeg', 'si7', 'ifm', 'ifs', 'si6', 'jpg', 'svg', 'rf', 'tiff', 'pbm', 'xbm', 'ppm', 'xpm', 'jpz', 'dcx', 'pcx', 'fhc', 'wpng', 'svh', 
                  'gif', 'fif', 'ief', 'tif', 'svf', 'nbmp', 'xwd', 'wbmp', 'eri', 'rgb', 'png', 'mil', 'jpe', 'wi', 'rp'], 
        'chemical': ['xyz', 'emb', 'embl', 'mop', 'csml', 'csm', 'gau', 'pdb', 'mol'], 'workbook': ['vts'], '*': [''], 'drawing': ['dwf'], 'i-world': ['ivr']}