# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qq_pic_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='qq_pic_message.proto',
  package='QQPicMessagepackage',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14qq_pic_message.proto\x12\x13QQPicMessagepackage\"\xb6\x01\n\x0emsg_pic_detail\x12\x19\n\x11picNameWithSuffix\x18\x01 \x01(\t\x12\x17\n\x0fpicNameNoSuffix\x18\x06 \x01(\t\x12\x14\n\x0cthumbPicPath\x18\x08 \x01(\t\x12\x11\n\tthumbPicW\x18\x16 \x01(\x05\x12\x11\n\tthumbPicH\x18\x17 \x01(\x05\x12\x0f\n\x07\x62igPicW\x18\x18 \x01(\x05\x12\x0f\n\x07\x62igPicH\x18\x19 \x01(\x05\x12\x12\n\nbigPicPath\x18  \x01(\t\"U\n\x10msg_1035_section\x12\x0f\n\x07welcome\x18\x01 \x01(\t\x12\x30\n\x03pic\x18\x02 \x01(\x0b\x32#.QQPicMessagepackage.msg_pic_detail\">\n\x08msg_1035\x12\x32\n\x03msg\x18\x01 \x03(\x0b\x32%.QQPicMessagepackage.msg_1035_sectionb\x06proto3')
)




_MSG_PIC_DETAIL = _descriptor.Descriptor(
  name='msg_pic_detail',
  full_name='QQPicMessagepackage.msg_pic_detail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='picNameWithSuffix', full_name='QQPicMessagepackage.msg_pic_detail.picNameWithSuffix', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='picNameNoSuffix', full_name='QQPicMessagepackage.msg_pic_detail.picNameNoSuffix', index=1,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thumbPicPath', full_name='QQPicMessagepackage.msg_pic_detail.thumbPicPath', index=2,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thumbPicW', full_name='QQPicMessagepackage.msg_pic_detail.thumbPicW', index=3,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thumbPicH', full_name='QQPicMessagepackage.msg_pic_detail.thumbPicH', index=4,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bigPicW', full_name='QQPicMessagepackage.msg_pic_detail.bigPicW', index=5,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bigPicH', full_name='QQPicMessagepackage.msg_pic_detail.bigPicH', index=6,
      number=25, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bigPicPath', full_name='QQPicMessagepackage.msg_pic_detail.bigPicPath', index=7,
      number=32, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=228,
)


_MSG_1035_SECTION = _descriptor.Descriptor(
  name='msg_1035_section',
  full_name='QQPicMessagepackage.msg_1035_section',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='welcome', full_name='QQPicMessagepackage.msg_1035_section.welcome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pic', full_name='QQPicMessagepackage.msg_1035_section.pic', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=315,
)


_MSG_1035 = _descriptor.Descriptor(
  name='msg_1035',
  full_name='QQPicMessagepackage.msg_1035',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='QQPicMessagepackage.msg_1035.msg', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=379,
)

_MSG_1035_SECTION.fields_by_name['pic'].message_type = _MSG_PIC_DETAIL
_MSG_1035.fields_by_name['msg'].message_type = _MSG_1035_SECTION
DESCRIPTOR.message_types_by_name['msg_pic_detail'] = _MSG_PIC_DETAIL
DESCRIPTOR.message_types_by_name['msg_1035_section'] = _MSG_1035_SECTION
DESCRIPTOR.message_types_by_name['msg_1035'] = _MSG_1035
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msg_pic_detail = _reflection.GeneratedProtocolMessageType('msg_pic_detail', (_message.Message,), dict(
  DESCRIPTOR = _MSG_PIC_DETAIL,
  __module__ = 'qq_pic_message_pb2'
  # @@protoc_insertion_point(class_scope:QQPicMessagepackage.msg_pic_detail)
  ))
_sym_db.RegisterMessage(msg_pic_detail)

msg_1035_section = _reflection.GeneratedProtocolMessageType('msg_1035_section', (_message.Message,), dict(
  DESCRIPTOR = _MSG_1035_SECTION,
  __module__ = 'qq_pic_message_pb2'
  # @@protoc_insertion_point(class_scope:QQPicMessagepackage.msg_1035_section)
  ))
_sym_db.RegisterMessage(msg_1035_section)

msg_1035 = _reflection.GeneratedProtocolMessageType('msg_1035', (_message.Message,), dict(
  DESCRIPTOR = _MSG_1035,
  __module__ = 'qq_pic_message_pb2'
  # @@protoc_insertion_point(class_scope:QQPicMessagepackage.msg_1035)
  ))
_sym_db.RegisterMessage(msg_1035)


# @@protoc_insertion_point(module_scope)
