# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wechat_story_comments.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wechat_story_comments.proto',
  package='wechat_story_comments_package',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bwechat_story_comments.proto\x12\x1dwechat_story_comments_package\";\n\x13WechatStoryUnknown1\x12\x11\n\tunknown_1\x18\x01 \x01(\x05\x12\x11\n\tunknown_2\x18\x02 \x01(\t\"\x9a\x01\n\x16WechatStoryCommentItem\x12\x19\n\x11\x63omment_parent_id\x18\x01 \x01(\x03\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x13\n\x0breceiver_id\x18\x03 \x01(\t\x12\x19\n\x11receiver_nickname\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\"\xaa\x02\n\x12WechatStoryComment\x12\x10\n\x08story_id\x18\x01 \x01(\x03\x12\x16\n\x0estory_owner_id\x18\x02 \x01(\t\x12\x1c\n\x14story_owner_nickname\x18\x03 \x01(\t\x12\x19\n\x11story_create_time\x18\x04 \x01(\x05\x12\x11\n\tunknown_1\x18\x05 \x01(\x05\x12\x45\n\tunknown_2\x18\x06 \x01(\x0b\x32\x32.wechat_story_comments_package.WechatStoryUnknown1\x12\x11\n\tunknown_3\x18\x07 \x01(\x05\x12\x44\n\x05items\x18\x08 \x03(\x0b\x32\x35.wechat_story_comments_package.WechatStoryCommentItemb\x06proto3')
)




_WECHATSTORYUNKNOWN1 = _descriptor.Descriptor(
  name='WechatStoryUnknown1',
  full_name='wechat_story_comments_package.WechatStoryUnknown1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown_1', full_name='wechat_story_comments_package.WechatStoryUnknown1.unknown_1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unknown_2', full_name='wechat_story_comments_package.WechatStoryUnknown1.unknown_2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=121,
)


_WECHATSTORYCOMMENTITEM = _descriptor.Descriptor(
  name='WechatStoryCommentItem',
  full_name='wechat_story_comments_package.WechatStoryCommentItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='comment_parent_id', full_name='wechat_story_comments_package.WechatStoryCommentItem.comment_parent_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender_id', full_name='wechat_story_comments_package.WechatStoryCommentItem.sender_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_id', full_name='wechat_story_comments_package.WechatStoryCommentItem.receiver_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_nickname', full_name='wechat_story_comments_package.WechatStoryCommentItem.receiver_nickname', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='wechat_story_comments_package.WechatStoryCommentItem.timestamp', index=4,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='wechat_story_comments_package.WechatStoryCommentItem.content', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=278,
)


_WECHATSTORYCOMMENT = _descriptor.Descriptor(
  name='WechatStoryComment',
  full_name='wechat_story_comments_package.WechatStoryComment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='story_id', full_name='wechat_story_comments_package.WechatStoryComment.story_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='story_owner_id', full_name='wechat_story_comments_package.WechatStoryComment.story_owner_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='story_owner_nickname', full_name='wechat_story_comments_package.WechatStoryComment.story_owner_nickname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='story_create_time', full_name='wechat_story_comments_package.WechatStoryComment.story_create_time', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unknown_1', full_name='wechat_story_comments_package.WechatStoryComment.unknown_1', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unknown_2', full_name='wechat_story_comments_package.WechatStoryComment.unknown_2', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unknown_3', full_name='wechat_story_comments_package.WechatStoryComment.unknown_3', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='wechat_story_comments_package.WechatStoryComment.items', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=579,
)

_WECHATSTORYCOMMENT.fields_by_name['unknown_2'].message_type = _WECHATSTORYUNKNOWN1
_WECHATSTORYCOMMENT.fields_by_name['items'].message_type = _WECHATSTORYCOMMENTITEM
DESCRIPTOR.message_types_by_name['WechatStoryUnknown1'] = _WECHATSTORYUNKNOWN1
DESCRIPTOR.message_types_by_name['WechatStoryCommentItem'] = _WECHATSTORYCOMMENTITEM
DESCRIPTOR.message_types_by_name['WechatStoryComment'] = _WECHATSTORYCOMMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WechatStoryUnknown1 = _reflection.GeneratedProtocolMessageType('WechatStoryUnknown1', (_message.Message,), dict(
  DESCRIPTOR = _WECHATSTORYUNKNOWN1,
  __module__ = 'wechat_story_comments_pb2'
  # @@protoc_insertion_point(class_scope:wechat_story_comments_package.WechatStoryUnknown1)
  ))
_sym_db.RegisterMessage(WechatStoryUnknown1)

WechatStoryCommentItem = _reflection.GeneratedProtocolMessageType('WechatStoryCommentItem', (_message.Message,), dict(
  DESCRIPTOR = _WECHATSTORYCOMMENTITEM,
  __module__ = 'wechat_story_comments_pb2'
  # @@protoc_insertion_point(class_scope:wechat_story_comments_package.WechatStoryCommentItem)
  ))
_sym_db.RegisterMessage(WechatStoryCommentItem)

WechatStoryComment = _reflection.GeneratedProtocolMessageType('WechatStoryComment', (_message.Message,), dict(
  DESCRIPTOR = _WECHATSTORYCOMMENT,
  __module__ = 'wechat_story_comments_pb2'
  # @@protoc_insertion_point(class_scope:wechat_story_comments_package.WechatStoryComment)
  ))
_sym_db.RegisterMessage(WechatStoryComment)


# @@protoc_insertion_point(module_scope)
